const jsonBrawlers =[
  { "name": "8bit", "image": "8bit_portrait.png", "rarities": {"rarity": "super rare", "hexa": "#0087fa", }},
  { "name": "Amber", "image": "amber_portrait.png", "rarities": {"rarity": "legendary", "hexa": "#fff11e", }},
  { "name": "Ash", "image": "ash_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Barley", "image": "barley_portrait.png", "rarities": {"rarity": "rare", "hexa": "#2edd1c", }},
  { "name": "Bea", "image": "bea_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Belle", "image": "belle_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Bibi", "image": "bibi_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Bo", "image": "bo_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Bonnie", "image": "bonnie_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Brock", "image": "brock_portrait.png", "rarities": {"rarity": "rare", "hexa": "#2edd1c", }},
  { "name": "Bull", "image": "bull_portrait.png", "rarities": {"rarity": "rare", "hexa": "#2edd1c", }},
  { "name": "Buster", "image": "buster_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Buzz", "image": "buzz_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Byron", "image": "byron_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Carl", "image": "carl_portrait.png", "rarities": {"rarity": "super rare", "hexa": "#0087fa", }},
  { "name": "Charlie", "image": "charlie_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Chester", "image": "chester_portrait.png", "rarities": {"rarity": "legendary", "hexa": "#fff11e", }},
  { "name": "Chuck", "image": "chuck_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Colette", "image": "colette_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Colt", "image": "colt_portrait.png", "rarities": {"rarity": "rare", "hexa": "#2edd1c", }},
  { "name": "Cordelius", "image": "cordelius_portrait.png", "rarities": {"rarity": "legendary", "hexa": "#fff11e", }},
  { "name": "Crow", "image": "crow_portrait.png", "rarities": {"rarity": "legendary", "hexa": "#fff11e", }},
  { "name": "Darryl", "image": "darryl_portrait.png", "rarities": {"rarity": "super rare", "hexa": "#0087fa", }},
  { "name": "Doug", "image": "doug_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Dynamike", "image": "dynamike_portrait.png", "rarities": {"rarity": "super rare", "hexa": "#0087fa", }},
  { "name": "Edgar", "image": "edgar_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "El Primo", "image": "elprimo_portrait.png", "rarities": {"rarity": "rare", "hexa": "#2edd1c", }},
  { "name": "Emz", "image": "emz_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Eve", "image": "eve_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Fang", "image": "fang_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Frank", "image": "frank_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Gale", "image": "gale_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Gene", "image": "gene_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Gray", "image": "gray_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Griff", "image": "griff_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Grom", "image": "grom_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Gus", "image": "gus_portrait.png", "rarities": {"rarity": "super rare", "hexa": "#0087fa", }},
  { "name": "Hank", "image": "hank_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Jacky", "image": "jacky_portrait.png", "rarities": {"rarity": "super rare", "hexa": "#0087fa", }},
  { "name": "Janet", "image": "janet_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Jessie", "image": "jessie_portrait.png", "rarities": {"rarity": "super rare", "hexa": "#0087fa", }},
  { "name": "Kit", "image": "kit_portrait.png", "rarities": {"rarity": "legendary", "hexa": "#fff11e", }},
  { "name": "Leon", "image": "leon_portrait.png", "rarities": {"rarity": "legendary", "hexa": "#fff11e", }},
  { "name": "Lola", "image": "lola_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Maisie", "image": "maisie_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Mandy", "image": "mandy_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Max", "image": "max_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Meg", "image": "meg_portrait.png", "rarities": {"rarity": "legendary", "hexa": "#fff11e", }},
  { "name": "Mico", "image": "mico_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Mortis", "image": "mortis_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Mr. P", "image": "mrp_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Nani", "image": "nani_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Nita", "image": "nita_portrait.png", "rarities": {"rarity": "rare", "hexa": "#2edd1c", }},
  { "name": "Otis", "image": "otis_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Pam", "image": "pam_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Pearl", "image": "pearl_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Penny", "image": "penny_portrait.png", "rarities": {"rarity": "super rare", "hexa": "#0087fa", }},
  { "name": "Piper", "image": "piper_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Poco", "image": "poco_portrait.png", "rarities": {"rarity": "rare", "hexa": "#2edd1c", }},
  { "name": "Rico", "image": "rico_portrait.png", "rarities": {"rarity": "super rare", "hexa": "#0087fa", }},
  { "name": "Rosa", "image": "rosa_portrait.png", "rarities": {"rarity": "rare", "hexa": "#2edd1c", }},
  { "name": "RT", "image": "rt_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Sam", "image": "sam_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Sandy", "image": "sandy_portrait.png", "rarities": {"rarity": "legendary", "hexa": "#fff11e", }},
  { "name": "Shelly", "image": "shelly_portrait.png", "rarities": {"rarity": "starting brawler", "hexa": "#94d7f4", }},
  { "name": "Spike", "image": "spike_portrait.png", "rarities": {"rarity": "legendary", "hexa": "#fff11e", }},
  { "name": "Sprout", "image": "sprout_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Stu", "image": "stu_portrait.png", "rarities": {"rarity": "epic", "hexa": "#b116ed", }},
  { "name": "Surge", "image": "surge_portrait.png", "rarities": {"rarity": "legendary", "hexa": "#fff11e", }},
  { "name": "Tara", "image": "tara_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
  { "name": "Tick", "image": "tick_portrait.png", "rarities": {"rarity": "super rare", "hexa": "#0087fa", }},
  { "name": "Willow", "image": "willow_portrait.png", "rarities": {"rarity": "mythic", "hexa": "#ff0020", }},
]